  <footer>
    <div class="footer-content">
        <p>&copy; 2026 G05 Quokka Recovery Program</p>

        <div class="footer-links">
            <a href="https://g05-applied-web-project.atlassian.net/jira/software/projects/SCRUM/boards/1"
               target="_blank">
                Jira Project
            </a>

            <a href="https://github.com/106009537/g05-applied-web-project.git"
               target="_blank">
                GitHub Repository
            </a>

            <a href="mailto:106009537@student.swin.edu.au">
                contact@quokkarecoveryprogram.org
            </a>
        </div>
    </div>
</footer>
  
</body>
</html>